adopted-ember-addons/ember-sortable

- README.md
- addon/mixins/sortable-item.js
- tests/dummy/app/styles/app.css
- tests/dummy/app/templates/application.hbs
> Add handle property to sortable-item

- addon/mixins/sortable-item.js
- addon/utils/transitionend.js
- tests/unit/utils/transitionend-test.js
> Detect correct transitionend event

- addon/mixins/sortable-item.js
- tests/unit/mixins/sortable-item-test.js
> Use run loop to schedule _complete

- README.md
- addon/components/sortable-group.js
- addon/mixins/sortable-item.js
- tests/dummy/app/routes/application.js
- tests/dummy/app/styles/app.css
- tests/dummy/app/templates/application.hbs
- tests/dummy/config/environment.js
- tests/unit/mixins/sortable-item-test.js
- add ability to sort in horizontal direction;
- new computed;
- add horizontal to demo;
- some more informative test app;
> Horizontal sorting

- addon/mixins/sortable-item.js
> Call _super in didInsertElement

- README.md
> Remove the line about discovering the parent group

- CHANGELOG.md
- addon/mixins/sortable-item.js
- tests/dummy/app/styles/app.css
- tests/dummy/app/templates/application.hbs
> Support tables

- addon/components/sortable-group.js
- addon/mixins/sortable-item.js
- tests/unit/components/sortable-group-test.js
This is #34 from @scottmessinger with js hint fixes
> Dragged model

- addon/mixins/sortable-item.js
> Fix touch support

- addon/mixins/sortable-item.js
- tests/.jshintrc
- tests/acceptance/smoke-test.js
- tests/dummy/app/templates/application.hbs
- tests/helpers/reorder.js
- tests/test-helper.js
This adds a full-on acceptance tests and introduces the `reorder` helper (to be extracted a little further down the road).
Partially addresses #6
> Better tests

- addon/mixins/sortable-item.js
- tests/helpers/drag.js
> Ignore right-click (and ctrl-click on OS X)

- addon/mixins/sortable-item.js
- tests/dummy/app/styles/app.css
This fixes some glitches in Firefox and (hopefully) the issues mentioned in #71.
> Flush styles in reset and thaw

- addon/helpers/drag.js
Needed in reaction to https://github.com/emberjs/ember.js/pull/12575
> Backfill triggerEvent in drag for Ember >= 2.5

- .npmignore
- addon/mixins/sortable-item.js
Fix for bug related at: https://github.com/jgwhite/ember-sortable/issues/86
> Fix for the infinite drag bug

- tests/dummy/app/components/sortable-item-mixin.js
- tests/unit/components/sortable-item-mixin-test.js
closes #109
- create mock component for testing
- move mixin tests to component
> Fix mixin unit tests

- addon/components/sortable-group.js
- addon/mixins/sortable-item.js
- package.json
closes #85
- add ember-invoke-action dependency
- replace sendAction usage
> Replace sendAction with ember-invoke-action

- addon/components/sortable-group.js
- addon/components/sortable-item.js
- addon/helpers/drag.js
- addon/helpers/reorder.js
- addon/mixins/sortable-item.js
- addon/system/utils.js
- app/components/sortable-group.js
- app/components/sortable-item.js
- package.json
- test-support/helpers/ember-sortable/test-helpers.js
- yuidoc.json
- add ember-cli-yuidoc and yuidoc-ember-theme as dependencies
- fix documentation in classes
TODO before next release (not in this PR)
- improve travis build so gh-pages branch is automatically updated
- add link to docs in dummy app
/cc @jgwhite
> Add API documentation via yuidoc

- addon/mixins/sortable-item.js
Had a similar issue to https://github.com/jgwhite/ember-sortable/issues/129
Needed this fix to solve the issue
> wrap _drag & _complete with isDestroyed/isDestroying check

- testem.js
- tests/unit/components/sortable-group-test.js
Works around https://github.com/travis-ci/travis-ci/issues/8836
> Use --no-sandbox testem config

- .eslintrc.js
- addon/components/sortable-group.js
- addon/mixins/sortable-item.js
- package.json
- yarn.lock
Replaces ember-invoke-action in favor of closure actions.
Fixes #169
> Remove ember-invoke-action

- addon/mixins/sortable-item.js
See: https://github.com/heroku/ember-sortable/issues/217
> replace window.releaseEvents with window.removeEventListener

- addon/mixins/sortable-item.js
Fixes https://github.com/heroku/ember-sortable/issues/219
I've started at the tests a bit and I'm not sure how to test this. The problem is that to test it I need test helpers that don't add a runloop themselves (which is an incorrect many test helpers used to do).
I'll first need to ascertain that the test helpers really are adding runloop wrapping.
> Runloop tweaks

- addon/helpers/drag.js
@fivetanley while investigating #226 I noticed this discrepancy.
> Tweak clientHeight calculation in drag helper

- README.md
> Add warning to polyfill `Element.closest()`

- package.json
> move @ember/jquery to devDependency

- addon/mixins/sortable-item.js
- tests/unit/components/sortable-item-mixin-test.js
see https://deprecations.emberjs.com/v3.x/#toc_jquery-event
Fixes #186
> Expect native events instead of jQuery wrapped events

- CHANGELOG.md
- package.json
Thanks to @stephencattaneo for #259!
> Release 1.12.9

- README.md
- index.js
- vendor/polyfills/closest.js
1.  Adding closest polyfill
2. Adding downloads badge
Manually tested on IE11.
Addresses #241
> Closest polyfill

- addon/components/sortable-group.js
- addon/components/sortable-handle.js
- addon/components/sortable-item.js
- addon/templates/components/sortable-group.hbs
- addon/utils/keyboard.js
- config/environment.js
- package.json
- test-support/ember-sortable/utils/keyboard.js
- tests/acceptance/smoke-test.js
- tests/dummy/app/styles/app.css
- tests/dummy/app/templates/application.hbs
- tests/unit/components/sortable-group-test.js
- yarn.lock
1. Added keyboard support
2. Added focus manage
TODOs:
- Fix tests
- Work on migration doc (I think we might deprecate some old APIs to encourage people to use better and accessible approaches, which this new addition is meant to tackel).
> Adding built-in keyboard support and focus management

- addon/components/sortable-group.js
- addon/components/sortable-item.js
- tests/acceptance/smoke-test.js
- tests/dummy/app/controllers/application.js
- tests/dummy/app/styles/app.css
- tests/dummy/app/templates/application.hbs
1. Adding API for enabling consumers to supply visual indicators to style on item and/or handles, such as highlighting and arrows.
2. Added examples to vertical and horizontal in the demo.
TODO:
~~1. Add tests.~~
> Visual Indicators

- addon/components/sortable-group.js
- addon/components/sortable-handle.js
- addon/components/sortable-item.js
- addon/styles/components/sortable-group.css
- addon/utils/constant.js
- tests/dummy/app/controllers/application.js
- tests/dummy/app/templates/application.hbs
Adding API for using an announcement config for different keyboard operations
> add aria-live announcement

- MIGRATION_GUIDE_V2.md
- README.md
> Updating README.md and adding migration guide

- index.js
> Attempt to fix vendor on consuming app production build

- addon/components/sortable-item.js
- tests/acceptance/smoke-test.js
- tests/dummy/app/templates/application.hbs
- tests/unit/components/sortable-item-test.js
Fixes https://github.com/adopted-ember-addons/ember-sortable/issues/231
> Added check for transitionDuration to isAnimated

- .travis.yml
- config/ember-try.js
3.15 is official release for `octane`
> [Ember try] Adding 3.15 to list of scenarios

- addon/modifiers/sortable-group.js
- tests/acceptance/smoke-modifier-test.js
- tests/dummy/app/templates/modifier.hbs
Fixes https://github.com/adopted-ember-addons/ember-sortable/issues/379
> Fixed modifier tracking correct dropped item with keyboard events

- package.json
- yarn.lock
Fixes https://github.com/adopted-ember-addons/ember-sortable/issues/383
> Upgraded ember-modifier to 2.1.0

- package.json
> Move `ember-get-config` to `dependencies`

- addon/components/sortable-group.js
- addon/modifiers/sortable-group.js
> Remove event.stopPropagation from focusOut

- package.json
- yarn.lock
close https://github.com/adopted-ember-addons/ember-sortable/issues/441
https://github.com/simplabs/ember-test-selectors/blob/master/CHANGELOG.md#v600-2021-07-05
> Bump ember-test-selectors v6.0.0

- addon/modifiers/sortable-item.js
Time to see if we can get the tests passing....
https://github.com/adopted-ember-addons/ember-sortable/pull/452
close #454
> bugfix: Ensure horizontal scrolling can go negative

- MIGRATION_GUIDE_MODIFIERS.md
fix type in modifier migration doc
> fix type in modifier migration doc

- addon/modifiers/sortable-group.js
- addon/modifiers/sortable-item.js
> Resolve `ember-modifier.no-args-property` deprecation warnings

- .github/workflows/plan-release.yml
- .github/workflows/publish.yml
- package.json
- pnpm-lock.yaml
pnpm8 redid the lockfile a bit.
This fixes the automated release.
> Upgrade to pnpm-8

- addon/src/modifiers/sortable-item.ts
Today i was running into an issue, in which the js error doesn't comes to console..., is totally hidden... there is no try/catch inside addon and also inside app, which blocks error throwing...
Steps to reproduce:
1. Clone https://github.com/adopted-ember-addons/ember-sortable
2. Make `pnpm i`
3. `cd test-app`
4. `ember s`
5. Remove `@action` in this line https://github.com/adopted-ember-addons/ember-sortable/blob/325228b1a4ecec41e2153f42520cec0fc7acf55a/test-app/app/controllers/index.js#L62
6. Add a `console.log` at begin of update function and after the first set...
7. Drag now an item from `Vertical list` or other one and you will see that it doesn't work and you will get no js error... btw. its not a `set` helper issue, because i don't use that in my app
If you add a try/catch into …
> Use native `Promise` instead from `rsvp`
