README.md
addon/components/sortable-group.js
tests/dummy/app/routes/application.js
tests/dummy/app/templates/application.hbs
tests/unit/components/sortable-group-test.js
tests/unit/mixins/sortable-item-test.js

So that `reorderItems` action handler knows which model it is modifying.
Updated code examples in README.
per #22

Explicitly supply the model source

---

package.json

Ember addons can now provide a demoURL which provides users with a demo link on ember observer.com and emberaddons.com.
See example from [ember-modal-dialog](https://github.com/yapplabs/ember-modal-dialog) (implemented in [this commit](https://github.com/yapplabs/ember-modal-dialog/commit/83ce265b9159ba3270ced967e55a82a64d154cd8)):
* [emberaddons.com](http://www.emberaddons.com/?query=ember-modal-dialog)
* [emberobserver.com](http://emberobserver.com/addons/ember-modal-dialog)
You probably need to publish a new version to npm - I'll leave that up to you (:

Add Ember Addon 'demoURL'

---

addon/components/sortable-group.js
addon/mixins/sortable-item.js
package.json

This is to implement the new computed property syntax to removes deprecation warning from Ember 1.13.
If you are Ok with only supporting Ember v1.12.0-beta.1+ then the use of a plugin can be removed - let me know if you would prefer to go that way and I'll update the PR.

New Computed Syntax

---

addon/mixins/sortable-item.js
tests/dummy/app/templates/application.hbs

Ran into this because we're using SVGs for our icons & it didn't recognise that the handle was being dragged. This uses `closest` instead just to check that we're dragging something which is either the handle, or inside the handle.
Couldn't see any existing tests for handles, but added an inner span to the dummy app as this triggers the problem.

Use `closest` vs `is` to support complex handles (e.g. SVG)

---

README.md
addon/mixins/sortable-item.js
tests/dummy/app/routes/application.js
tests/unit/mixins/sortable-item-test.js

I had the need to change a property in my parent template when something was dragging vs when it wasn't. Following the "Data Down, Actions Up", this seemed like the cleanest implementation.
I don't care for testing private methods but I didn't think it warranted a full on event and such for just testing these actions.
I also removed a `console.log` that didn't seem to add any benefits. If there was a reason for that, just let me know.
Happy to take feedback.

Add actions for `onDragStart` and `onDragStop`

---

README.md

Adds two missing closing brackets to one of the examples in the README.

Fix typos in example

---

README.md
addon/helpers/drag.js
addon/helpers/reorder.js
bower.json
test-support/helpers/ember-sortable/test-helpers.js
tests/test-helper.js

Drag-and-drop interactions are very difficult to test. Consumers of this
addon would like to test their application's interactions with the
addon.
Exposing `drag` and `reorder` gives consumers the tools to verify that
they're interacting with the addon properly.

Expose `drag` and `reorder` test helpers

---

README.md

As a consumer of the `test-support` helpers, importing in
`tests/test-helper.js` causes issues.
To resolve these issues, recommend that consumers import the helpers as
part of `tests/helpers/start-app.js` instead.

Fix test imports usage in README

---

.gitignore
README.md
addon/components/sortable-group.js
addon/mixins/sortable-item.js
tests/dummy/app/styles/app.css
tests/dummy/app/templates/application.hbs
tests/unit/components/sortable-group-test.js

This PR introduces a new property to ember-sortable: the spacing which appears after dragging an element. When users starts to drag element, other elements jump back, which is a nice visual effect. It works both for the x and y option;
In `y` case elements above current one jump up, and elements below current one - jump down.
In `x` case elements before current one jump to the left, and elements after current one - jump to the right.
The `spacing` is defined for each item which uses the `sortable-item` mixin (and can be different for each of the elements).

A new sortable-item property: spacing

---

addon/mixins/sortable-item.js

A simple fix to prevent errors when sortables are dragged outside the boundaries of a containing `{{ember-modal-dialog}}` component.

Fix for dragging outside of ember-modal-dialog boundaries

---

addon/mixins/sortable-item.js

`cancelStartDragListener` is retaining components in tests due to the event listener not always being torn down. When I was tracking down memory leaks in our application, we found that this method was one of the points in our test suite that would retain a bunch of memory (~9Mb or so) through our test run of 1,000 tests.
This fixes #110

Remove event listeners in willDestroyElement

---

addon/mixins/sortable-item.js
addon/system/scroll-container.js
addon/system/scroll-parent.js
tests/dummy/app/styles/app.css

This builds in functionality to scroll the container when a `{{sortable-item}}` reaches the bounding edge of its parent scroll container.
Some more work is needed to get scrolling smooth when the browser window is the element that should scroll, but it works wonderfully in scrollable containers. To test, you can try dragging items to the edges of the browser window and the page should move :)

Autoscroll while dragging sortable-items

---

addon/helpers/drag.js
tests/dummy/app/styles/app.css

This is a fix for #105. I've updated the `drag` helper to apply a scaling factor to `dx` and `dy`, which fixes the failing tests when running under `ember-cli-qunit` 3.0, and should remain compatible with 2.x as well.

Fix test helpers in ember-cli-qunit 3.0

---

addon/components/sortable-group.js
addon/mixins/sortable-item.js
tests/unit/components/sortable-group-test.js
tests/unit/components/sortable-item-test.js

Adds (optional) attribute bindings for `data-test-selector` to the `sortable-group` and `sortable-item` component. 
Not a critical change, rather an improvement for test ergonomics in consuming applications, by following a widely adopted convention around testing with page objects.

adds support for 'data-test-selector' attribute

---

addon/system/scroll-parent.js

Fix #116 by using the document instead of the body element as the scroll parent.

Use document as the scroll parent if the body is the scroll parent

---

README.md

Going by your ember-try testing on Travis, this is your minimum supported ember version. Is it correct, and do you want a badge for it?

publicize supported ember versions

---

addon/components/sortable-group.js
addon/mixins/sortable-item.js
package.json

As a result of #127, it appears you do not need this polyfill anymore, as it targets ember versions prior to 1.12.0-beta.1.

remove unused ember-new-computed polyfill

---

addon/mixins/sortable-item.js

closes #130
- chrome 56 breaks the sortable-item touch events by setting them to passive by default. Because of this, we need to set ‘touch-action: false’ on a handle if it exists, or the entire element if it doesn’t
I'm also going to cherry-pick this commit onto the new branch, `1.x` that I created, and release a new version under 1.9.2 (because of the recently introduced breaking changes).

Prevent touch-actions on element or handle using css

---

README.md
addon/helpers/drag.js
addon/mixins/sortable-item.js
tests/acceptance/smoke-test.js
tests/dummy/app/styles/app.css
tests/dummy/app/templates/application.hbs
tests/integration/components/sortable-group-test.js

I took a different approach from the existing PR. With this PR, the drag functionality is not registered until the node is dragged more than the passed distance.
Let me know if you have any comments.

Add distance attribute, for when sorting should start

---

addon/mixins/sortable-item.js

These are a couple of small changes to try to reduce the likelihood of typos and omissions during the event registration and teardown operations. I've also added [namespaces](http://api.jquery.com/on/) to events so that while debugging orphaned `window` events, developers can see an `emberSortable` namespace reported to identify their source.

Cleanup listener registration

---

addon/utils/slot.js

The combination of calling `css` and then `height` as in `node.$().css(...).height()` was causing a recalculate styles -> relayout for **each** slot. In my app, this increased performance of the `clear` function by approximately 1000x (1300ms -> 1.3ms). Granted, my app has a bit over 200 draggable elements, so the difference is more pronounced. In more normal apps, the change should still be noticeable.

Dramatically increase performance by reducing relayout

---

addon/mixins/sortable-item.js

Somehow we needed this when our item was an Ember #link-to.
Without this we couldn't get the sorting to work.

Fix when surrounded by ember link-to

---

addon/mixins/sortable-item.js

This "fix" is kind of related with the autoscroll feature that was added on `1.8.3`. If the dragged element height is higher than its container, the autoscroll starts moving automatically. This change does not fix that, but allows that overriding element's height (by a css class for example) gets correctly calculated. 
Please let me know if I was clear enough or if you guys need some demo.

make `_scrollOnEdges()` get `itemContainer` height dinamically

---

addon/mixins/sortable-item.js
tests/unit/components/sortable-item-mixin-test.js

While debugging an issue in an application, we came across a case where the act of dragging an element caused re-renders and actively-dragging-element destruction.
In this scenario, ember-sortable would endlessly scroll the page to the top of the screen because the `isDragging` flag remained true (once dragging began) even after the element was destroyed. This occurred because the `_scrollOnEdges` method uses `requestAnimationFrame` to recursively call itself while dragging. If the element is destroyed and isDragging is forever true, these recursive calls will never end.

Disable isDragging when element is destroyed

---

addon/mixins/sortable-item.js

We are using this addon in an application where `group` is already a thing in many places.
Therefore we would like to use a different name for that variable.
With this change we only have to override `_direction` and `_tellGroup` instead of having to copy complete methods.
Let me know if this is desired or if you know a better way!

Alias sortable direction to group

---

addon/mixins/sortable-item.js

fixes #132. 
`_drag` was being invoked after `reset` was called on the item, and after a drop.

fix for issue with transforms being left after drop

---

README.md
addon/mixins/sortable-item.js
tests/integration/components/sortable-group-test.js

This enables simple keyboard-based accessible sorting via  a `keyUp` handler.
For example:
```hbs
{{#each myItems as |item idx| }}
{{#sortable-item tabindex=0 keyUp=(action 'keyUp' idx) model=item }}
{{item.name}}
{{/sortable-item}}
{{/each}}
```
```js
actions: {
keyUp(index, evt) {
switch(evt.key) {
case "ArrowDown":
// move item at `index` back one
break;
case "ArrowUp":
// move item at `index` forward one
break;
default:
return;
}
}
}
```

Add tabindex attribute binding

---

addon/mixins/sortable-item.js

I am working removing memory leaks across test runs in a very large ember app. I noticed that jquery seems to maintain a reference to the element here because of the event listener. I thought this was a bit strange as I expected the listener would be eligible for garbage collection once the element is removed from the dom. However, I believe the issue is that jquery maintains a cache of elements passed to its constructor and does not know to update its internal cache if the element is removed using native apis or some other non-jquery technique. The result is when when the test run is complete, there is an application container instance that cannot be garbage collected. This should not affect any logic or functionality. just notifies jquery that the listener should be removed when the …

Remove jquery event listener from component element

---

tests/unit/components/sortable-group-test.js
tests/unit/components/sortable-item-mixin-test.js

`targetObject` is deprecated in favor of `target` ([see more](https://www.emberjs.com/deprecations/v2.x/#toc_code-targetobject-code)). Fixes ##167
This fixes tests that used `targetObject`. They pass 100%

Fix deprecation warnings for targetObject

---

addon/components/sortable-group.js
addon/mixins/sortable-item.js
package.json
yarn.lock

This was a polyfill for ember 1.11 apps which seems ok to remove at this point since I can't think of many reasons someone would be stuck on 1.11 at this point (and the testing matrix for this addon only tests 2.x anyhow)
Closes https://github.com/jgwhite/ember-sortable/issues/166

remove ember-new-computed

---

addon/components/sortable-group.js

Addon breaks in Ember 3.4 if Array extensions are disabled

Don't break if A extensions are not enabled

---

addon/system/scroll-container.js

My last PR incorrectly was calling `getComputedStyle` on `window` doesn't work, so current master will throw an error.
Used the same calc that jQuery uses to do `$(window).width()/height()`

Fix incorrect ScrollContainer dimension calcs

---

.travis.yml
addon/helpers/drag.js
addon/helpers/waiters.js
addon/mixins/sortable-item.js
test-support/helpers/ember-sortable/test-helpers.js
testem.js
tests/acceptance/smoke-test.js
tests/test-helper.js

- SVGs don't have height in Firefox, so we have to fallback to the
parentElement's height in order to calculate scale correctly. When the
`drag` handler was used on a `.handle` element that was an SVG, the
value of `scale` was always zero. Now it is the correct value (usually
1).
- Use the `transitionend` event to wait for events to finish. This prevents race conditions versus trying to extract the time from the styles. In chrome,
these animations were scheduled in such a way that the dom elements were
technically in the right order but visually inaccurate if we slowed the
transitions down. In Firefox, the smoke tests failed due to the elements
being out of order. In addition to using the `transitionend` event
(which is supported by all browsers we …

fixes for Firefox

---

addon/helpers/drag.js
tests/acceptance/smoke-test.js

When using `drag` in tests, it's common to only drag vertically or
horizontaly, and leave either `dx` or `dy` undefined. When `dx` or `dy`
is undefined, the math calculated by the `drag` helper returns NaN
(because multiplying by undefined or null returns `NaN` instead), which
can throw errors when performing the drag in tests.
This fixes the helper by defaulting `dx` or `dy` to 0, a valid number,
instead.

[bugfix] default `dx` and `dy` to 0 for drag helper

---

addon/mixins/sortable-item.js

When using `document.querySelector(this.get('handle'))` in order to find the element with the dragging handle, the first matching element in the whole DOM is returned. 
The consequence is that only the first element in a sortable list has the inline style `touch-action:none`. If the list had *n* members, the current code would match the first element in the list *n* times, applying the style only to that element *n* times in an idempotent way.
The fix scopes the query to the actual element which has just been inserted in the DOM so as to guarantee that each draggable element gets the inline style.

inline `touch-action:none` not being properly applied

---

README.md
addon/templates/components/sortable-group.hbs
testem.js
tests/dummy/app/templates/application.hbs
tests/integration/components/sortable-group-test.js

PR changes `{{sortable-group}} ` so it now yields `{{sortable-item}}`:
```hbs
{{#sortable-group onChange=(action "reorderItems") as |group|}}
{{#each model.items as |item|}}
{{#group.item model=item handle=".handle"}}
{{item.name}}
<span class="handle">&varr;</span>
{{/sortable-item}}
{{/each}}
{{/sortable-group}}
```
---
- cleaner and more flexible API since all `group<=>item` communication details can now be hidden from addon user
- easy of future improvements (for example #154)
- backwards incompatible*
- dropping Ember <2.4 support (6% of users according to [latest survey](https://emberjs.com/ember-community-survey-2019/))
`*` this may be done backwards compatible but with a bit weird API

{{sortable-item}} as сlosure component

---

addon/mixins/sortable-item.js

In the shift to a jQuery-less future this method wasn’t converted quite correctly.
Fixes #240

Fix subtle bug in sortable-item#thaw

---

.travis.yml
config/ember-try.js

I'd like to ensure ember-sortable remains backwards compatible to Ember 1.12. I'd welcome any feedback from maintainers about if that is something they are OK with, or if not then to get some reasoning about what the base version should be.
Regardless this PR is an incremental change to add Ember 2.8 and 2.12 support to the test suite. I'll follow up on any failures.

Add Ember 2.8, 2.12 to testing. Test Node 8.

---

.eslintrc.js

Have eslint enforce that we want `() => {}` not `()=>{}`

eslint: enforce space before and after arrow of arrow function

---

addon/mixins/sortable-item.js

When using ember-sortable inside a list that scrolls, the `getY / getX` function inside sortable-item mixin returns `undefined` causing the calculation of item position to get confused and ultimately end up being `NaN`. The reason it gets mixed up is because the event being passed into `getY(event)` has the property `pageY` instead of the (currently) expected `clientY`. This PR fixes the `undefined` by giving priority to `clientY/clientX` while falling back to `pageY/pageX`
Where getY is getting called with the wrong event. 
https://github.com/heroku/ember-sortable/blob/master/addon/mixins/sortable-item.js#L536
Originating from:
https://github.com/heroku/ember-sortable/blob/master/addon/mixins/sortable-item.js#L489
Before: 
https://screencast-o-matic.com/watch/cqQ0oLtRJD
After: …

[BUGFIX] fixes bug when sorting to the beginning of list

---

addon/system/scroll-container.js

This fixes the broken scrolling for elements inside overflow: auto/scroll containers.

Properly convert ScrollContainer width and height to integers

---

addon/components/sortable-group.js
addon/components/sortable-item.js
package.json
tests/dummy/app/controllers/application.js
tests/dummy/app/routes/application.js
tests/dummy/app/templates/application.hbs
tests/unit/components/sortable-group-test.js
tests/unit/components/sortable-item-test.js
yarn.lock

This will cause backward incompatbility if a consumer is passing in `actions` as `strings`, e.g
`onDragStart="onDragStart"` instead of `onDragStart=(action "onDragStart")`

Deprecating sendAction

---

addon/components/sortable-handle.js
addon/components/sortable-item.js
addon/templates/components/sortable-item.hbs
app/components/sortable-handle.js
tests/acceptance/smoke-test.js
tests/dummy/app/templates/application.hbs

This will be the last PR to finish moving ember-sortable to become fully composable.
Also updated demo and all affected tests.
The benefit seems to be that the migration path is very straightforward!
Props to @H1D for initiating this.

Adding sortable-handle

---

package.json
yarn.lock

Moving ember-test-waiters and ember-test-selectors from devDependencies to dependencies to solve #304

[Bugfix] ember-test-waiters

---

README.md

Addresses the confusion regarding `group=group` in #306

Remove group=group from README

---

addon/components/sortable-group.js
addon/components/sortable-item.js
tests/unit/components/sortable-group-test.js

Giving it a shot.
Had to use `defineProperty` workaround to ensure compatibility with consumers that  do not have ember versions `3.10` and up.

Deprecating volatile in favor of native getter and setter

---

test-support/ember-sortable/helpers/drag.js

👋 Thanks for maintaining this addon!
We recently ran into a case where we wanted to test application state while a drag was in-progress, before the final 'mouseup' was triggered. Would you accept this PR that adds a `beforedragend` optional callback?

Add beforedragend callback to `drag` helper

---

addon/templates/components/sortable-group.hbs
addon/templates/components/sortable-item.hbs

External consumer fails in integration test b/c `sortable-item` couldn't be found.

Adding ember-sortable to the yield scope

---

addon/components/sortable-group.js
addon/components/sortable-item.js
addon/templates/components/sortable-group.hbs
tests/unit/components/sortable-group-test.js
tests/unit/components/sortable-item-test.js

The method of passing down the `group` into the `item` is a bit flaky. Seems like due to the timing of the `runloop scheduler`, functions such as `registerItem` aren't properly registered on the `group` when it needs to be available for the caller.
Moving to a more `action`-based approach seems to potentially mitigate this problem and remove the dependency on the `runloop scheduler`. It also seems like the better Ember practice, supporting the Data Down Action Up paradigm.
Could potentially mitigate #306

Refactoring group into actions and pass actions instead

---

addon/components/sortable-item.js

the coordinates util relies on clientY and clientX being available on the event passed to it. When creating a fakeEvent in the scrollOnEdges method, only pageX/Y was being passed. This commit adds in the clientX/Y coordinates as well to allow the existing getX/Y util to function properly
*Note* I wasn't able to come up with a suitable acceptance test as Im unable to trigger an event programmatically that mimics the browser behaviour. Manual testing has worked. If you have any ideas on how I might test this, I'd be happy to amend
Thanks!

[BUGFIX] Fixes scrolling outside of an overflow container's boundaries resolves#346

---

addon/modifiers/sortable-item.js

Noticed that the supplied `onDragStart` handler was getting called twice and this seems to explain why. Looks like a simple refactoring mistake which slipped through in the previous beta release.

Actually use `onDragStop` argument rather then re-using `onDragStart`.

---

addon/modifiers/sortable-item.js
tests/acceptance/smoke-modifier-test.js

I noticed that the handle does not work correctly within the modifiers version: Even when it is present, the whole sortable element is draggable. We should probably still add some tests that try to sort by trying to move a sortable element where a handler is present.

fixes handle when using modifiers

---

README.md

Corrects a few typos in the modifier sections of the README, where `{{group.item}}` was being referenced instead of the `{{sortable-item}}` modifier

Correct typos in modifier examples

---

README.md
addon/modifiers/sortable-group.js
addon/modifiers/sortable-item.js
addon/services/ember-sortable.js
tests/acceptance/smoke-modifier-test.js
tests/dummy/app/templates/modifier.hbs
tests/integration/modifiers/sortable-group-test.js
tests/unit/services/ember-sortable-test.js

This PR uses a service instead of item after render to register and maintain state.
This does require that is there is more than one group in the DOM that both the group and items contain an additional param of the group name.

Use a service to track group/item state

---

package.json
yarn.lock

This upgrades ember-cli-babel to v7. Also removed `ember-native-class-polyfill` since it's not needed anymore

upgrade ember-test-selectors to v4

---

.github/workflows/github_ci.yml
config/ember-try.js

Updated to using LTS versions, `3.12`, `3.16`, and `3.20`. Keep `3.8` around for backward compatibility check even tho it is no longer LTS.

Updating github actions ci to use lts ember versions in ember try

---

package.json
yarn.lock

Resolves getWithDefault deprecation.
**Release Notes for 5.0.0**
https://github.com/simplabs/ember-test-selectors/blob/master/CHANGELOG.md#v500-2020-09-02

fix(deprecation): update ember-test-selectors

---

addon/modifiers/sortable-group.js

In some cases the willRemove method is run after the page has navigated away. Therefore we should check if the announcer still has a parentNode before trying to remove it.

Fixes "'removeChild' of null" in SortableGroupModifier willRemove method

---

yarn.lock

This reverts commit 468ee0c653260d65bf6cc4035dfdee29bb68bb70 (from #403), reversing changes made to 3ccf38b7581639e35e12ca64758fc42a956f00af. The merge was done in error, and it breaks against Ember 3.20 LTS for reasons not yet clear.

Revert "Merge pull request #403 from adopted-ember-addons/dependabot/npm_and_yarn/ini-1.3.7

---

README.md
config/ember-try.js
index.js
package.json
yarn.lock

This removes the ember-decorator-polyfill dependency and instead adds a console warning if the consuming app doesn't have it installed. The issue here is that the polyfill breaks older versions of ember-data when used with the newest versions of ember-source. For users stuck on old versions of ember-data due to performance regressions this can be an issue. 
Fixes #378

Require ember-decorators-polyfill to be installed by client app

---

README.md
addon/components/sortable-item.js
addon/modifiers/sortable-item.js
package.json
yarn.lock

- Update ember-cli-babel to @7.26.6
- Octanify README example
- Fix eslint getter-return warning https://eslint.org/docs/rules/getter-return
- Fix computed imports

Update ember-cli-babel to @7.26.6, update README example

---

tests/dummy/app/controllers/index.js
tests/dummy/app/styles/app.css
tests/dummy/app/templates/index.hbs
tests/dummy/app/templates/modifier.hbs

I was looking at the table example and realized that a11y wasn't being announced because the aria live region was being added into the table., not outside of the table breaking table semantics. I also made sure the table semantics are proper for both component and modifer versions.
Before:
After:

Update the table examples to be more proper

---

package.json
yarn.lock

I've been having authentication issues with `npm`, and figured that getting the `release-it` packages upgraded to their latest versions might help.
From what I can tell... it did not fix my problems. But upgrading these packages doesn't hurt anyway!

Upgrade `release-it` packages

---

addon/modifiers/sortable-group.js
addon/modifiers/sortable-item.js

Extract `cleanup` to a function in module scope which accepts an
instance as its public argument, and use that when calling
`registerDestructor` as well as at the start of every `modify` call.
This results in having exactly one function allocated for the
destructor to call, instead of a function per instance. This is a
relatively small win, but a meaningful one which might add up
significantly if you have many of these on a given page.

perf: avoid creating callbacks for the destructor

---

RELEASE.md
package.json

Note that during this the labels on GH were also updated.
This was created with https://github.com/rwjblue/create-rwjblue-release-it-setup

chore: update release process to match adopted standards

---

addon/modifiers/sortable-item.js
tests/acceptance/smoke-modifier-test.js
tests/dummy/app/components/cells/day-of-week/index.hbs
tests/dummy/app/components/cells/fruit/index.hbs
tests/dummy/app/components/cells/sortable/index.hbs
tests/dummy/app/components/row/component.js
tests/dummy/app/components/row/template.hbs
tests/dummy/app/components/table/template.hbs
tests/dummy/app/controllers/index.js
tests/dummy/app/templates/index.hbs

Related issue: https://github.com/adopted-ember-addons/ember-sortable/issues/492
```hbs
{{#if this.isEven}}
<Cells::Sortable @index={{@index}} />
{{else}}
<Cells::Sortable @index={{@index}} class="odd-class"/>
{{/if}}
```
(refer to the animation in the issue)
1. start the demo with `ember serve`
2. Using your mouse (it's faster) click on the demo I created
3. Use TAB to select a fruit
4. Use ENTER to go into drag mode
5. Use ARROW KEYS to move
6. Use ENTER/SPACE to commit
7. Repeat steps 1-6 more than 3 times. It should work every time.
`ember test` should also pass.

fix: Handle element in sortable item should be the most recent

---

addon/modifiers/sortable-item.js
package.json
yarn.lock

This replaces the ember-get-config based setup with the [`isTesting` Embroider macro](https://github.com/embroider-build/embroider/tree/main/packages/macros#istesting-isdevelopingapp).
It simplifies the setup and allows us to drop ember-get-config.

Use the `isTesting` macro

---

config/environment.js
tests/dummy/config/environment.js

This moves the `ember-a11y-testing` config into the dummy app's environment file. This prevents the config from being merged with the consuming app's config while it is only needed for the addon tests.

Move test config to the dummy app

---

addon/modifiers/sortable-item.js

the sortableGroup getter returns the groupModifier, which may be undefined.
when fetchGroup is called in the service: https://github.com/adopted-ember-addons/ember-sortable/blob/master/addon/services/ember-sortable.js#L87
undefined is passed as the modifier.
This requires that https://github.com/adopted-ember-addons/ember-sortable/blob/master/addon/modifiers/sortable-group.js#L729
is invoked, which has no protection around it :thinking: 
An alternative could be that we need to throw some protection around this situation from happening -- which I'm still investigating locally.
But these changes "get tests passing" in the ember-sortable@2 -> ember-sortable@3 upgrade PR I have internally.

sortableGroup may be undefined

---

addon/modifiers/sortable-item.js

This PR makes sure event listeners on sortable-item are only added when the item is not disabled, as it appears to be a waste of resources to add event listeners to an element where they are not needed. Sortable group already does not register listeners when in disabled state. 
Background: In a template, I do not want to maintain a list for display purposes and a separate list for editing. Therefore I would like to have a list that where I can enable editing, that does not consume unnecessary resources in display state.
This PR makes #353 obsolete.

when item is disabled, do not add event listeners

---

addon/package.json

These dependencies are common enough that we'll want to defer to the consuming app's version of them to improve compatibility.
Tests are failing because yarn can't handle peer dependencies.
Guess this repo is switching to pnpm now.
Gonna merge the red PR, because too many things need to change for v5 prep, and release-it requires single-change, single-PR type workflow

Move common dependencies to peer dependencies (ember-modifier, @ember/test-helpers, @ember/test-waiters)

---

.github/workflows/ci.yml
addon/package.json
package.json
pnpm-lock.yaml
test-app/config/ember-try.js
test-app/package.json

@ember/test-helpers v3 has been released for a while.

Allow @ember/test-helpers 3

---

addon/package.json

so we don't have work to do when our declared peers have majors

widen peer ranges

---

.github/workflows/plan-release.yml
.github/workflows/publish.yml
CHANGELOG.md
RELEASE.md
addon/package.json
package.json
pnpm-lock.yaml

Sets up: https://github.com/embroider-build/release-plan
The more-automated replacement for release-it, allowing releases from the couch, car, you name it.
Changes:
1. `❯ npx create-release-plan-setup@latest --update`
2. remove release-it.

Setup release-plan

---

addon/package.json

Looks like none of the `_app_` files are importable.
this is an issue I thought we would have encountered sooner:
```
You tried to reverse exports for the file
`./dist/_app_/modifiers/sortable-group.js` 
in package `ember-sortable` but it does not match any 
of the exports rules defined in package.json. 
This means it should not be possible to access directly.
```
ember-sortable _is_ a v2 addon already, but forgot to re-export their `_app_` directory:
```
"exports": {
".": "./dist/index.js",
"./modifiers/*": "./dist/modifiers/*",
"./services/*": "./dist/services/*",
"./test-support": "./dist/test-support/index.js",
"./addon-main.js": "./addon-main.js"
},
```
:sweat_smile:
Discussion: https://discord.com/channels/480462759797063690/1182017862651629601/1182019040785473566 
--------------_ …

importing from the _app_ directory was disallowed because of the exports config.

---

.github/workflows/plan-release.yml
.github/workflows/publish.yml

Uses the same action-setup-pnpm action as ci.yml.
This allows the package.json to control node and pnpm versions everywhere.

Use consistent setup action in the other workflows

---

addon/src/modifiers/sortable-item.js
addon/src/test-support/helpers/drag.js

While added direction `grid` in PR #560 we have discovered, that the waiting for `transitionEnd` was not correctly. This has some side-effects in tests, when using with a bigger list of item, because the animation spents more time.
This was the reason, why added tests for direction `grid` were failed.
This PR fix following bugs
1. dropend and was already called before all transitions of all items was completed
2. after dropping a item and taking an other one immediately, brings crazy transition effect and sometime also order was not anymore correct
3. in tests the `drop` helper hasn't respected `transitionEnd`, caused by the other two bugs. Fast reordering like in tests are not working with large lists

Fix: Block drag start while any item is busy & add wait for transition end in test helper `drop`

---

README.md

After adding the `grid` direction, we have forgot to add this info into ReadMe docs.
While adding this info i have also found some parts that were not anymore correctly

Add info about `grid` direction into readme and minimal fixes

---

addon/src/modifiers/sortable-item.js
test-app/tests/integration/modifiers/sortable-item-test.js

In our app we have seen that when we have only one item we are running into error `TypeError: items[0] is undefined` this is caused, because the `filter` returns possible a empty array
The bug was introduced by adding direction `grid` https://github.com/adopted-ember-addons/ember-sortable/pull/560
Workaround in our app (since this bugfix landes) is to add `disabled` on group

Fix error `TypeError: items[0] is undefined` in `sortable-item` modifier

---

.github/workflows/ci.yml
addon/package.json
pnpm-lock.yaml
test-app/package.json

More/less always while building addon we are running into the error that tests do fail... `prepublishOnly` runs at same time like `build`.
Removing `prepublishOnly` (which makes the same as build) should fix the randomly fails

Remove `prepublishOnly` in favor of `prepack` script to fix randomly test failing

---

addon/package.json

Like reported in discord typings are not working because declaration export is missing
https://discord.com/channels/480462759797063690/491905849405472769/1288552863890407588

Add missing declaration export for modifier, services & test-support

---

addon/src/modifiers/sortable-group.ts

fix #590 
While TS migration we have added a bug (i think its a copy / paste 🙈 bug)
Bug line:
https://github.com/adopted-ember-addons/ember-sortable/pull/581/files#diff-5939f3d31bd0123e82fb032af95f429af12caf252af3044a3ec495e3214c9476R785

Fix direction x (calculation incorrect)

---

addon/src/modifiers/sortable-group.ts
addon/src/modifiers/sortable-item.ts

In ember v6.3 there was added deprecation for service import from inject https://deprecations.emberjs.com/id/importing-inject-from-ember-service/
This changes allows us to hold support for `ember-source` <= 4.0 ([see changelog](https://github.com/emberjs/ember.js/blob/main/CHANGELOG.md#v410-december-28-2021)) and removes deprecation in newer versions

Cleanup `@ember/service` deprecation

---

addon/package.json

- ember-source: removed because the embroider / auto-import know what we intend - it's not bad to have if someone manages their dep graph correctly, which is easier with pnpm, but not everyone gets it right, and folks have a hard time tracking down errors
- @glimmer/tracking removed because it's a real package, but one we don't want to use. This comes up in embroider/vite where the presence of real packages always takes precedence over virtual packages. This is actually problematic because it can break reactivity in subtle ways, even if a dep graph is correct - allowing duplicates of dependencies, which for the glimmer internals, we don't want.
ref https://github.com/ember-cli/ember-addon-blueprint/pull/35

Remove unneeded peer dependency on ember-source

---

addon/src/modifiers/sortable-item.ts

In else-case there a check which will never `true`

Remove unnecessary condition check for `this.isAnimated`
